### ISSUE TITLE
图片不清晰

### ISSUE THREAD

**Issue by kuangwushijian** [TuTouPower/How-to-connect-internet#1]
朋友，我最近也在看这本书，看到你的总结图片非常棒，但是看不清晰，可以分享清晰一点的图片吗，谢谢啦！

**Comment by ZhangNanBei** [comment]
你好，github上已开源此图片及其工程文件，链接如下。
https://github.com/ZhangNanBei/How-to-connect-internet



图片的链接如下
https://github.com/ZhangNanBei/How-to-connect-internet/blob/main/%E7%BD%91%E7%BB%9C%E6%98%AF%E6%80%8E%E6%A0%B7%E8%BF%9E%E6%8E%A5%E7%9A%84.jpg

| |
张锋
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年5月4日 ***@***.***> 写道：

朋友，我最近也在看这本书，看到你的总结图片非常棒，但是看不清晰，可以分享清晰一点的图片吗，谢谢啦！

**Comment by kuangwushijian** [comment]
老哥，可以加你微信吗，想问一些关于春招的事？
我的微信，19916944659
